server:
 port: 8081

spring:
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL55Dialect
  database: mysql
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:mysql://db:3306/bookstore
  username: root
  password: 123456